---
extends: existence
message: Use "broadcast" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#broadcast-v
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  broad cast|broad-cast
