---
extends: existence
message: Use "built-in" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#built-in
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  builtin|built in
