---
extends: existence
message: Use "app" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#app
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  app.
