---
extends: existence
message: Use "bare-metal" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#bare-metal-adj
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  baremetal|bare metal
