---
extends: existence
message: Use "BIND" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#bind
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  Bind|bind
