---
extends: existence
message: Use "BIOS" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#bios
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  Bios
