---
extends: existence
message: Use "biweekly" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#biweekly
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  bi-weekly
