---
extends: existence
message: Use "CDs" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#cds
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  CDS|Cds
