---
extends: existence
message: Use "ciphertext" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#ciphertext
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  cipher text|cyphertext|cypher text|cipher-text|cypher-text
