---
extends: existence
message: Use "cloudwashing" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#cloudwashing
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  cloud-washing
