---
extends: existence
message: Use "cloudbursting" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#cloudbursting
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  cloud-bursting
