---
extends: existence
message: Use "command-driven" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#command-driven
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  command driven|commanddriven
