---
extends: existence
message: Use "CSV" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#csv
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  csv
