---
extends: existence
message: Use "debug" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#debug-adj
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  de-bug
