---
extends: existence
message: Use "denial-of-service" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#denial-of-service-adj
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  Denial-of-Service
