---
extends: existence
message: Use "DevOps" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#devops-n
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  devops|Devops|Dev-Ops|Dev Ops
