---
extends: existence
message: Use "disk label" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#disk-label
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  disklabel|disk-label
