---
extends: existence
message: Use "DNS" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#dns
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  dns
