---
extends: existence
message: Use "dual-boot" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#dual-boot
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  dualboot|dual boot
