---
extends: existence
message: Use "DVD writer" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#DVD-writer
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  DVD burner|burner
