---
extends: existence
message: Use "emit" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#emit
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  send out
