---
extends: existence
message: Use "Enter" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#enter-n
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  
