---
extends: existence
message: Use "environment" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#environment
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  
