---
extends: existence
message: Use "event" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#event
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  
