---
extends: existence
message: Use "examine" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#examine
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  look at
