---
extends: existence
message: Use "Exif" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#exif
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  EXIF|exif
