---
extends: existence
message: Use "FAQ" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#faq
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  Faq|faq|F.A.Q
