---
extends: existence
message: Use "Fedora™ Project" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#fedora-project
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  fedora project
