---
extends: existence
message: Use "firmware" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#firmware
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  firm ware|firm-ware
