---
extends: existence
message: Use "foreground" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#foreground
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  fore-ground|forground
