---
extends: existence
message: Use "GB" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#gb
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  gb|Gb
