---
extends: existence
message: Use "Gbps" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#gbps
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  gbps|GBPS
