---
extends: existence
message: Use "GID" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#gid
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  gid|Gid
