---
extends: existence
message: Use "GIMP" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#gimp
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  Gimp|gimp
