---
extends: existence
message: Use "GNOME" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#gnome
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  Gnome|gnome
