---
extends: existence
message: Use "GPL" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#gpl
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  Gpl|gpl
