---
extends: existence
message: Use "GRUB" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#grub
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  Grub
