---
extends: existence
message: Use "GTK+" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#gtkplus
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  GTK|Gtk|gtk
