---
extends: existence
message: Use "hard code" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#hard-code
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  hardcode
