---
extends: existence
message: Use "health check" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#health-check
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  healthcheck|health-check
