---
extends: existence
message: Use "hotline" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#hotline
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  hot-line
