---
extends: existence
message: Use "hyperconverged" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#hyperconverged
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  hyper-converged
