---
extends: existence
message: Use "Hyper-Threading" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#hyper-threading
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  hyperthreading|hyper-threading
