---
extends: existence
message: Use "hypervisor" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#hypervisor
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  HyperVisor|Hyperviser
