---
extends: existence
message: Use "IBM Z" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#ibm-z
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  IBM z Systems
