---
extends: existence
message: Use "installation program" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#installation-program
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  the installer
