---
extends: existence
message: Use "IOPS" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#iops
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  Iops|IOPs
