---
extends: existence
message: Use "Itanium" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#itanium
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  IA64|ia64
