---
extends: existence
message: Use "Kernel-based Virtual Machine" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#kernel-based-virtual-machine
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  kernel-based virtual machine
