---
extends: existence
message: Use "kernel-space" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#kernel-space-ad
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  kernelspace
