---
extends: existence
message: Use "Kickstart" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#kickstart
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  kickstart
