---
extends: existence
message: Use "Knowledgebase" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#knowledgebase
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  KnowledgeBase
