---
extends: existence
message: Use "KVM" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#kvm
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  kvm
