---
extends: existence
message: Use "LAN" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#lan
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  Lan|lan
