---
extends: existence
message: Use "man page" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#man-page
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  manpage
