---
extends: existence
message: Use "Microsoft" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#microsoft
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  MS|MSFT|MicroSoft
