---
extends: existence
message: Use "Mozilla Firefox" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#mozilla-firefox
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  firefox
