---
extends: existence
message: Use "now" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#now
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  right now
