---
extends: existence
message: Use "OK" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#ok
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  OK button
