---
extends: existence
message: Use "omit" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#omit
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  leave out
