---
extends: existence
message: Use "opcode" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#opcodes
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  op-code
