---
extends: existence
message: Use "performance counter" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#performance-counter
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  perfcounter
