---
extends: existence
message: Use "plain text" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#plain-text
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  plaintext|plain-text|cleartext|clear text
