---
extends: existence
message: Use "POSIX" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#posix
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  Posix|posix|variations
