---
extends: existence
message: Use "PowerPC" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#powerpc
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  PPC|P-PC|PPC64
