---
extends: existence
message: Use "PROM" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#prom
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  prom|Prom
