---
extends: existence
message: Use "proof of concept" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#proof-of-concept
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  proof of concepts
