---
extends: existence
message: Use "pseudo-ops" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#pseudoops
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  pseudo ops|pseudoops
