---
extends: existence
message: Use "pulldown" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#pulldown
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  pull-down
