---
extends: existence
message: Use "raw" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#raw
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  RAW
