---
extends: existence
message: Use "Red Hat Network Proxy Server" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#red-hat-network-proxy-server
ignorecase: true
nonword: true
level: error
source: SupplementaryStyleGuide
tokens:
    -  Red Hat Proxy \(Server\)
