---
extends: existence
message: Use "remote access server" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#remote-access-server
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  remote-access server
