---
extends: existence
message: Use "repository" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#repository
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  channel
