---
extends: existence
message: Use "rollout" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#rollout
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  roll out
