---
extends: existence
message: Use "ROM" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#rom
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  Rom|rom
