---
extends: existence
message: Use "roundtable" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#roundtable
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  round table
