---
extends: existence
message: Use "RPM" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#rpm
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  rpm
