---
extends: existence
message: Use "Samba" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#samba
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  samba|SAMBA
