---
extends: existence
message: Use "screen saver" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#screen-saver
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  screensaver
