---
extends: existence
message: Use "see" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#see
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  refer to
