---
extends: existence
message: Use "segmentation fault" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#segmentation-fault
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  segfault as a verb
