---
extends: existence
message: Use "server farm" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#server-farm
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  computer farm|computer ranch
