---
extends: existence
message: Use "Shadowman" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#shadowman
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  Shadow Man|ShadowMan
