---
extends: existence
message: Use "shadow passwords" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#shadow-passwords
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  Shadow passwords
