---
extends: existence
message: Use "SOCKS" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#socks
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  socks
