---
extends: existence
message: Use "Software Collection" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#software-collection
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  software collection|collection|Software collection|Collection
