---
extends: existence
message: Use "sound card" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#sound-card
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  soundcard|sound-card
