---
extends: existence
message: Use "spec file" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#spec-file
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  specfile
