---
extends: existence
message: Use "spelled" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#spelled
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  spelt
