---
extends: existence
message: Use "SSH" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#ssh
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  SSH as a verb
