---
extends: existence
message: Use "standalone" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#standalone
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  stand-alone
