---
extends: existence
message: Use "startx" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#startx
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  StartX
