---
extends: existence
message: Use "submenu" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#submenu
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  sub-menu
