---
extends: existence
message: Use "swap space" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#swap-space
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  swapspace
