---
extends: existence
message: Use "systemd" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#systemd
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  system D|system D|SystemD|system d|Systemd
