---
extends: existence
message: Use "text mode" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#text-mode
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  textmode|text-mode
