---
extends: existence
message: Use "throughput" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#throughput
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  thru
