---
extends: existence
message: Use "through" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#through
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  thru
