---
extends: existence
message: Use "tier-1" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#tier-1
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  tier-one|tier 1
