---
extends: existence
message: Use "time frame" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#time-frame
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  timeframe|time-frame
