---
extends: existence
message: Use "TTL" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#ttl
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  ttl
