---
extends: existence
message: Use "upsell" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#upsell
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  up-sell
