---
extends: existence
message: Use "upselling" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#upselling
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  up-selling|up selling
