---
extends: existence
message: Use "URL" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#url
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  url
