---
extends: existence
message: Use "user space" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#user-space-n
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  userspace
