---
extends: existence
message: Use "VAR" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#var
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  var
