---
extends: existence
message: Use "video mode" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#video-mode
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  video-mode|videomode
