---
extends: existence
message: Use "VLAN" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#vlan
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  vlan|vLAN
