---
extends: existence
message: Use "vNIC" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#vnic
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  vnic|VNIC|Virtual Network Interface Card
