---
extends: existence
message: Use "VPN" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#vpn
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  vpn
