---
extends: existence
message: Use "WAN" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#wan
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  wan
