---
extends: existence
message: Use "want" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#want
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  wish|would like
