---
extends: existence
message: Use "web UI" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#web-ui
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  web-UI|webUI
