---
extends: existence
message: Use "write" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#write
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  code
