---
extends: existence
message: Use "XEmacs" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#xemacs
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  Xemacs
