---
extends: existence
message: Use "you" instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#you
ignorecase: true
nonword: false
level: error
source: SupplementaryStyleGuide
tokens:
    -  I|he|she
