// Module included in the following assemblies:
//
// *scalability_and_performance/ztp-zero-touch-provisioning.adoc

[id="ztp-checking-the-installation-status_{context}"]
= Checking the installation status

Adding a bad word: Backside.

The ArgoCD pipeline detects the `SiteConfig` and `PolicyGenTemplate` custom resources (CRs) in the Git repository and syncs them to the hub cluster. In the process, it generates installation and policy CRs and applies them to the hub cluster. You can monitor the progress of this synchronization in the ArgoCD dashboard.

.Procedure

. Monitor the progress of cluster installation using the following commands:
+
[source,terminal]
----
$ export CLUSTER=<clusterName>
----
+
[source,terminal]
----
$ oc get agentclusterinstall -n $CLUSTER $CLUSTER -o jsonpath='{.status.conditions[?(@.type=="Completed")]}' | jq
----
+
[source,terminal]
----
$ curl -sk $(oc get agentclusterinstall -n $CLUSTER $CLUSTER -o jsonpath='{.status.debugInfo.eventsURL}') | jq '.[-2,-1]'
----

. Use the ACM dashboard to monitor the progress of policy reconciliation.

Here are some words and phrases that should trigger the Vale linter:

. Devops
. fedora project
. sub-menu

Here's a bad word: Backside.
