name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@v1.4.0
      with:

        # Optional
        config: https://raw.githubusercontent.com/aireilly/vale-action-sandbox/main/vale.ini?token=ARU52DAP3MCLH6RNA7QLJULBKHRLM

        # Optional
        files: vale-action-sandbox/modules
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

