name: Linting
on: [pull_request]

jobs:
  vale-suggestions:
    name: runner / vale / suggestions
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: false
          reporter: github-check
          filter_mode: added
          token: ${{secrets.GITHUB_TOKEN}}
  vale-errors:
    name: runner / vale / errors
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
          vale_flags: "--minAlertLevel=error"
          reporter: github-check
          filter_mode: added
          token: ${{secrets.GITHUB_TOKEN}}